### ISSUE TITLE
Help me how to use this for custom iOS keyboard

### ISSUE THREAD

**Issue by gstream** [PoomSmart/MorePredict#1]
Hello @PoomSmart 

Thanks for sharing this project. I am seeking open source custom keyboard app which can provide next word prediction just similar with standard iOS prediction.

I am very interested in your project but stucking how to use it.

Would appreciate if you teach me how to use this project.

Hope to hearing from you soon.

Regards

**Comment by PoomSmart** [comment]
MorePredict doesn't focus on word prediction algorithm, instead unlocks the suggestion limit. As far as I know, such prediction algorithm exists that you may consult on the internet.
